### ISSUE TITLE
No Spotify Cover and no part of the right of the screen

### ISSUE THREAD

**Issue by pacmac34** [erikdubois/Aureola#27]
Hello,

my conky looks like this:  https://i.imgur.com/UdTL5Cx.png

It doesn't show spotify cover or the conky part of the right of the screen (I think it tries to show it to the left)

This is the conky output:

conky: desktop window (1e5) is root window
conky: window type - normal
conky: drawing to created window (0x7c00002)
conky: drawing to double buffer
conky: Unknown setting 'imlib_cache_size'
conky: unknown variable '$image'
conky: forked to background, pid is 31732
conky: can't open /sys/class/power_supply/BAT0/uevent: No existe el fichero o el directorio
conky: can't open /proc/acpi/battery/BAT0/state: No existe el fichero o el directorio
conky: can't open /proc/apm: No existe el fichero o el directorio
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147    0   147    0     0    653      0 --:--:-- --:--:-- --:--:--   665
conky: llua_do_call: function conky_main execution failed: /home/pacmac/.config/conky/main.lua:1259: attempt to concatenate global 'today_trans' (a nil value)

Thank you for sharing your work, this is an awesome theme.

**Comment by qmeeus** [comment]
I remember that I stumble upon the same problem a few months ago.

The last error (function conky_main execution failed) is probably the culprit to crashing conky. This is the problematic line in the code:
```cairo_show_text(cr,today_trans.."iB");```

And these are the lines causing the value of `today_trans` to be `nil`:
```
local stats = conky_parse("${execi 10 vnstat -i "..interface.."}");
```
Then,
```
_,nex,ntoday_trans = string.find(stats, "|%s*(.-)iB",nex);
if(ntoday_trans ~= nil) then
    today_trans = ntoday_trans;
end
-- print("tot: "..today_trans..'iB');
```

The output of vnstat is different depending on the distributions. The value of `ntoday_trans` is `nil` because the original parsing expression that works for Ubuntu is different from how you should parse it if you use Arch for example (or Gentoo in your case?). 

I guess the best way to solve your problem is to dig into the code and try to parse for yourself the output of vnstat... Lucky for you, lua is very easy to understand and the author was nice enough to only comment out the lines he used for debugging ;)

**Comment by erikdubois** [comment]
no more development on this github
